# Australopiteco Homo Habilis Homo Erectus Homo Neanderthalensis Homo Sapiens
print("Расположите по порядку стадии развития человека, поставив нужную порядковую цифру. Если всё будет верно, в конце вы получите правильное расположение цифр от 1 до 5.")
option1 = input("Australopiteco-")
option4 = input("Homo Neanderthalensis-")
option2 = input("Homo Habilis-")
option5 = input("Homo Sapiens-")
option3 = input("Homo Erectus-")
print(option1, option2, option3, option4, option5, sep='=>')
x=("Australopiteco")
y=("Homo Habilis")
q=("Homo Erectus")
e=("Homo Neanderthalensis")
w=("Homo Sapiens")
print(x, y, q, e, w, sep='=>')